/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-06-05 03:18:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class PayView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js\"></script>\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n");
      out.write(" \n");
      out.write("\n");
      out.write("<h1>Payment </h1>\n");
      out.write("<body>\n");
      out.write("<table>\n");
      out.write("<form role=\"form\">\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("    <label for=\"email\">Email address:</label>\n");
      out.write("    <input type=\"email\" class=\"form-control\" id=\"email\">\n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("    <label for=\"pwd\">Password:</label>\n");
      out.write("    <input type=\"password\" class=\"form-control\" id=\"pwd\">\n");
      out.write("  </div>\n");
      out.write("  <div class=\"checkbox\">\n");
      out.write("    <label><input type=\"checkbox\"> Remember me</label>\n");
      out.write("  </div>\n");
      out.write("  <button type=\"submit\" class=\"btn btn-default\">Submit</button>\n");
      out.write("</form>\n");
      out.write("<hr>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" href=\"http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css\">\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.11.3.min.js\"></script>\n");
      out.write("<script src=\"http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <div data-role=\"main\" class=\"ui-content\">\n");
      out.write("    <a href=\"#myPopup\" data-rel=\"popup\" class=\"ui-btn ui-btn-inline ui-corner-all ui-icon-check ui-btn-icon-left\"> Payment </a>\n");
      out.write("\n");
      out.write("    <div data-role=\"popup\" id=\"myPopup\" class=\"ui-content\" style=\"min-width:650px; \">\n");
      out.write("      <form method=\"post\" action=\"demoform.asp\">\n");
      out.write("        <div>\n");
      out.write("        <center>\n");
      out.write("          <h1>Payment information</h1>\n");
      out.write("          </center>\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("          <label for=\"usrnm\" >Card Holdrer's Name:</label>\n");
      out.write("          <input type=\"text\" name=\"user\" id=\"usrnm\" placeholder=\"Enter Card holder's Name :\">\n");
      out.write("          <label for=\"pswd\" >Card NUmebr :</label>\n");
      out.write("          <input type=\"password\" name=\"passw\" id=\"pswd\" placeholder=\"Enter Your Card Number.\">\n");
      out.write("          \n");
      out.write("          \n");
      out.write("          <label> Expiry Date:</label>\n");
      out.write("          <SELECT NAME=\"CCExpiresMonth\"  >\n");
      out.write("        <OPTION VALUE=\"\" SELECTED>--Month--\n");
      out.write("        <OPTION VALUE=\"01\">January (01)\n");
      out.write("        <OPTION VALUE=\"02\">February (02)\n");
      out.write("        <OPTION VALUE=\"03\">March (03)\n");
      out.write("        <OPTION VALUE=\"04\">April (04)\n");
      out.write("        <OPTION VALUE=\"05\">May (05)\n");
      out.write("        <OPTION VALUE=\"06\">June (06)\n");
      out.write("        <OPTION VALUE=\"07\">July (07)\n");
      out.write("        <OPTION VALUE=\"08\">August (08)\n");
      out.write("        <OPTION VALUE=\"09\">September (09)\n");
      out.write("        <OPTION VALUE=\"10\">October (10)\n");
      out.write("        <OPTION VALUE=\"11\">November (11)\n");
      out.write("        <OPTION VALUE=\"12\">December (12)\n");
      out.write("      </SELECT> /\n");
      out.write("      <SELECT NAME=\"CCExpiresYear\">\n");
      out.write("        <OPTION VALUE=\"\" SELECTED>--Year--\n");
      out.write("        <OPTION VALUE=\"04\">2004\n");
      out.write("        <OPTION VALUE=\"05\">2005\n");
      out.write("        <OPTION VALUE=\"06\">2006\n");
      out.write("        <OPTION VALUE=\"07\">2007\n");
      out.write("        <OPTION VALUE=\"08\">2008\n");
      out.write("        <OPTION VALUE=\"09\">2009\n");
      out.write("        <OPTION VALUE=\"10\">2010\n");
      out.write("        <OPTION VALUE=\"11\">2011\n");
      out.write("        <OPTION VALUE=\"12\">2012\n");
      out.write("        <OPTION VALUE=\"13\">2013\n");
      out.write("        <OPTION VALUE=\"14\">2014\n");
      out.write("        <OPTION VALUE=\"15\">2015\n");
      out.write("      </SELECT>\n");
      out.write("      \n");
      out.write("      <label for=\"usrnm\" > CVV :</label>\n");
      out.write("          <input type=\"text\" name=\"user\" id=\"usrnm\" placeholder=\"CVV\">\n");
      out.write("  \n");
      out.write("          <label for=\"log\">Remember</label>\n");
      out.write("          \n");
      out.write("          <input type=\"checkbox\" name=\"login\" id=\"log\" value=\"1\" data-mini=\"true\">\n");
      out.write("          <input type=\"submit\" data-inline=\"true\" value=\"Pay\">\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("      </form>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  \n");
      out.write("  </div>\n");
      out.write("</div> \n");
      out.write("</table>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "themeView.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
