/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-06-05 07:11:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class theatersView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <!-- Theme Made By www.w3schools.com - No Copyright -->\n");
      out.write("  <title>Bootstrap </title>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\n");
      out.write("  <link href=\"http://fonts.googleapis.com/css?family=Lato\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("  <link href=\"http://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js\"></script>\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n");
      out.write("  <style>\n");
      out.write("  body {\n");
      out.write("      font: 400 15px/1.8 Lato, sans-serif;\n");
      out.write("      background-color: black;\n");
      out.write("      color: #777;\n");
      out.write("  }\n");
      out.write("  h3, h4 {\n");
      out.write("      margin: 10px 0 30px 0;\n");
      out.write("      letter-spacing: 10px;      \n");
      out.write("      font-size: 20px;\n");
      out.write("      color: #111;\n");
      out.write("  }\n");
      out.write("  .container {\n");
      out.write("      padding: 80px 120px;\n");
      out.write("  }\n");
      out.write("  .person {\n");
      out.write("      border: 10px solid transparent;\n");
      out.write("      margin-bottom: 25px;\n");
      out.write("      width: 80%;\n");
      out.write("      height: 80%;\n");
      out.write("      opacity: 0.7;\n");
      out.write("  }\n");
      out.write("  .person:hover {\n");
      out.write("      border-color: #f1f1f1;\n");
      out.write("  }\n");
      out.write("  .carousel-inner img {\n");
      out.write("      -webkit-filter: grayscale(90%);\n");
      out.write("      filter: grayscale(80%); /* make all photos black and white */ \n");
      out.write("      width: 100%; /* Set width to 100% */\n");
      out.write("      margin: auto;\n");
      out.write("  }\n");
      out.write("  .carousel-caption h3 {\n");
      out.write("      color: #fff !important;\n");
      out.write("  }\n");
      out.write("  @media (max-width: 500px) {\n");
      out.write("    .carousel-caption {\n");
      out.write("      display: none; /* Hide the carousel text when the screen is less than 600 pixels wide */\n");
      out.write("    }\n");
      out.write("  }\n");
      out.write("  .bg-1 {\n");
      out.write("      background: #2d2d30;\n");
      out.write("      color: #bdbdbd;\n");
      out.write("  }\n");
      out.write("  .bg-1 h3 {color: #fff;}\n");
      out.write("  .bg-1 p {font-style: italic;}\n");
      out.write("  .list-group-item:first-child {\n");
      out.write("      border-top-right-radius: 0;\n");
      out.write("      border-top-left-radius: 0;\n");
      out.write("  }\n");
      out.write("  .list-group-item:last-child {\n");
      out.write("      border-bottom-right-radius: 0;\n");
      out.write("      border-bottom-left-radius: 0;\n");
      out.write("  }\n");
      out.write("  .thumbnail {\n");
      out.write("      padding: 0 0 15px 0;\n");
      out.write("      border: none;\n");
      out.write("      border-radius: 0;\n");
      out.write("  }\n");
      out.write("  .thumbnail p {\n");
      out.write("      margin-top: 15px;\n");
      out.write("      color: #555;\n");
      out.write("  }\n");
      out.write("  .btn {\n");
      out.write("      padding: 10px 20px;\n");
      out.write("      background-color: #333;\n");
      out.write("      color: #f1f1f1;\n");
      out.write("      border-radius: 0;\n");
      out.write("      transition: .2s;\n");
      out.write("  }\n");
      out.write("  .btn:hover, .btn:focus {\n");
      out.write("      border: 1px solid #333;\n");
      out.write("      background-color: #fff;\n");
      out.write("      color: #000;\n");
      out.write("  }\n");
      out.write("  .modal-header, h4, .close {\n");
      out.write("      background-color: #333;\n");
      out.write("      color: #fff !important;\n");
      out.write("      text-align: center;\n");
      out.write("      font-size: 30px;\n");
      out.write("  }\n");
      out.write("  .modal-header, .modal-body {\n");
      out.write("      padding: 40px 50px;\n");
      out.write("  }\n");
      out.write("  .nav-tabs li a {\n");
      out.write("      color: #777;\n");
      out.write("  }\n");
      out.write("  #googleMap {\n");
      out.write("      width: 100%;\n");
      out.write("      height: 400px;\n");
      out.write("      -webkit-filter: grayscale(100%);\n");
      out.write("      filter: grayscale(100%);\n");
      out.write("  }  \n");
      out.write("  .navbar {\n");
      out.write("      font-family: Montserrat, sans-serif;\n");
      out.write("      margin-bottom: 0;\n");
      out.write("      background-color: #2d2d30;\n");
      out.write("      border: 0;\n");
      out.write("      font-size: 11px !important;\n");
      out.write("      letter-spacing: 4px;\n");
      out.write("      opacity: 0.9;\n");
      out.write("  }\n");
      out.write("  .navbar li a, .navbar .navbar-brand { \n");
      out.write("      color: #d5d5d5 !important;\n");
      out.write("  }\n");
      out.write("  .navbar-nav li a:hover {\n");
      out.write("      color: #fff !important;\n");
      out.write("  }\n");
      out.write("  .navbar-nav li.active a {\n");
      out.write("      color: #fff !important;\n");
      out.write("      background-color: #29292c !important;\n");
      out.write("  }\n");
      out.write("  .navbar-default .navbar-toggle {\n");
      out.write("      border-color: transparent;\n");
      out.write("  }\n");
      out.write("  .open .dropdown-toggle {\n");
      out.write("      color: #fff;\n");
      out.write("      background-color: #555 !important;\n");
      out.write("  }\n");
      out.write("  .dropdown-menu li a {\n");
      out.write("      color: #000 !important;\n");
      out.write("  }\n");
      out.write("  .dropdown-menu li a:hover {\n");
      out.write("      background-color: transparent !important;\n");
      out.write("  }\n");
      out.write("  footer {\n");
      out.write("      background-color: #2d2d30;\n");
      out.write("      color: #f5f5f5;\n");
      out.write("      padding: 32px;\n");
      out.write("  }\n");
      out.write("  footer a {\n");
      out.write("      color: #f5f5f5;\n");
      out.write("  }\n");
      out.write("  footer a:hover {\n");
      out.write("      color: #777;\n");
      out.write("      text-decoration: none;\n");
      out.write("  }  \n");
      out.write("  .form-control {\n");
      out.write("      border-radius: 0;\n");
      out.write("  }\n");
      out.write("  textarea {\n");
      out.write("      resize: none;\n");
      out.write("  }\n");
      out.write("  </style>\n");
      out.write("  \n");
      out.write("  \n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("\tvar datefield = document.createElement(\"span\")\n");
      out.write("\tdatefield.setAttribute(\"type\", \"date\")\n");
      out.write("\tif (datefield.type != \"date\") {\n");
      out.write("\t\tdocument\n");
      out.write("\t\t\t\t.write('<link href=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css\" rel=\"stylesheet\" type=\"text/css\" />\\n')\n");
      out.write("\t\tdocument\n");
      out.write("\t\t\t\t.write('<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js\"><\\/script>\\n')\n");
      out.write("\t\tdocument\n");
      out.write("\t\t\t\t.write('<script src=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js\"><\\/script>\\n')\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("\tif (datefield.type != \"date\") {\n");
      out.write("\t\tjQuery(function($) {\n");
      out.write("\t\t\t$('#date').datepicker({\n");
      out.write("\t\t\t\tdateFormat : 'yy/mm/dd',\n");
      out.write("\t\t\t\tmaxDate : \"+6d\",\n");
      out.write("\t\t\t\tminDate : \"-0d\"\n");
      out.write("\t\t\t});\n");
      out.write("\t\t})\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t/* $('#psw').validate({rules: {\n");
      out.write("        id_material : {\n");
      out.write("            required : true,\n");
      out.write("            maxNumber : \"+5\",\n");
      out.write("            minNumber : \"+0\"\n");
      out.write("        }\n");
      out.write("    } }*/);\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body id=\"myPage\" data-spy=\"scroll\" data-target=\".navbar\" data-offset=\"50\">\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("  <div class=\"panel panel-default\">\n");
      out.write("  <h3>Select date</h3><input type=date placeholder=\"Select Date\" id=date style=\"width: 300px\" name=\"date\">\n");
      out.write("  <!-- <button type=\"button\"  id = date style = \"width:300px\"  name =date class=\"btn btn-default btn-sm\">\n");
      out.write("          <span class=\"glyphicon glyphicon-calendar\"></span> Calendar\n");
      out.write("        </button>\n");
      out.write("   -->   \n");
      out.write("    \n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<!-- theatre list stars here -->\n");
      out.write("\n");
      out.write("<div>\n");
      out.write("\t\t\t<!--<form action = \"ReserveController\">-->\n");
      out.write("<table align=\"center\" class=\"table table-bordered table-stripped\" >\n");
      out.write("<tr><th>Theater Name</th><th colspan=4 align=\"center\">Timings</th><th></th></tr>\n");
      out.write("<tr><td id=\"theater\"><a href = \"https://www.google.co.in/maps/place/Prasads+Large+Screen/@17.41287,78.4637323,17z/data=!3m1!4b1!4m5!3m4!1s0x3bcb975afb4afadd:0xf89ea8407df6c84!8m2!3d17.41287!4d78.465921?hl=en\">Prasads-Imax</a></td><td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">11:30</label>\n");
      out.write("    </div></td><td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">3:15</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">6:00</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">9:15</label>\n");
      out.write("    </div></td>\n");
      out.write("   <td><button class=\"btn\" data-toggle=\"modal\" data-target=\"#myModal\">BOOK</button></td></tr>\n");
      out.write("   \n");
      out.write("              <tr><td id=\"theater\"><a href =\"https://www.google.co.in/maps/place/Cinepolis+Multiplex+Cinema+Hall/@17.4130317,78.3956976,12z/data=!3m1!5s0x3bcb918d014210af:0xa0e81c6667b666c4!4m8!1m2!2m1!1sCinepolies!3m4!1s0x3bcb918cfe52a909:0xbb6f8f917c1d8997!8m2!3d17.4897758!4d78.3932155?hl=en\">Cinepolies</a></td><td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">11:30</label>\n");
      out.write("    </div></td><td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">3:15</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">6:00</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">9:15</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td><button class=\"btn\" data-toggle=\"modal\" data-target=\"#myModal\">BOOK</button></td></tr>\n");
      out.write("    <tr><td id=\"theater\"><a href = \"https://www.google.co.in/maps/place/Forum+Sujana+Mall/@17.4841317,78.3866975,17z/data=!3m1!4b1!4m5!3m4!1s0x3bcb91892fad42ab:0x45a52c5555381afb!8m2!3d17.4841317!4d78.3888862?hl=en\">Forum-Mall</a></td><td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">11:30</label>\n");
      out.write("    </div></td><td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">3:15</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">6:00</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">9:15</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td><button class=\"btn\" data-toggle=\"modal\" data-target=\"#myModal\">BOOK</button></td></tr>\n");
      out.write("    <tr><td id=\"theater\"><a href = \"https://www.google.co.in/maps/place/inorbit/@17.4410185,78.3898927,17z/data=!3m1!4b1!4m5!3m4!1s0x3bcb915c65fa9953:0xcfa71f78431e5be3!8m2!3d17.4410185!4d78.3920814?hl=en\">Inorbit-Mall</a></td><td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">11:30</label>\n");
      out.write("    </div></td><td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">3:15</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">6:00</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">9:15</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td><button class=\"btn\" data-toggle=\"modal\" data-target=\"#myModal\">BOOK</button></td></tr>\n");
      out.write("    <tr><td id=\"theater\"><a href =\"https://www.google.co.in/maps/place/GVK+One/@17.4192183,78.4463622,17z/data=!3m1!4b1!4m5!3m4!1s0x3bcb9736975c54b9:0xb24847634360df71!8m2!3d17.4192183!4d78.4485509?hl=en\">GVK One Mall</a></td><td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">11:30</label>\n");
      out.write("    </div></td><td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">3:15</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">6:00</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">9:15</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td><button class=\"btn\" data-toggle=\"modal\" data-target=\"#myModal\">BOOK</button></td></tr>\n");
      out.write("    <tr><td id=\"theater\"><a href =\"https://www.google.co.in/maps/place/Cine+Planet+Multiplex/@17.5294398,78.4835977,17z/data=!3m1!4b1!4m5!3m4!1s0x3bcb8551cc2375ed:0x365b2d3362aa5e02!8m2!3d17.5294398!4d78.4857864?hl=en\">CinePlanet</a></td><td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">11:30</label>\n");
      out.write("    </div></td><td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">3:15</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">6:00</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">9:15</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td><button class=\"btn\" data-toggle=\"modal\" data-target=\"#myModal\">BOOK</button></td></tr>\n");
      out.write("    <tr><td id=\"theater\"><a href =\"https://www.google.co.in/maps/place/Asian+GPR+Multiplex/@17.4508945,78.4111155,12z/data=!4m8!1m2!2m1!1sAsian+Multiplex!3m4!1s0x3bcb91f14f7f035f:0xa323880995867fd7!8m2!3d17.49918!4d78.390627?hl=en\">Asian Multiplex</a></td><td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">11:30</label>\n");
      out.write("    </div></td><td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">3:15</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">6:00</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">9:15</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td><button class=\"btn\" data-toggle=\"modal\" data-target=\"#myModal\">BOOK</button></td></tr>\n");
      out.write("    <tr><td id=\"theater\"><a href=\"https://www.google.co.in/maps/place/PVR+Cinemas/@17.4231815,78.4254997,17z/data=!3m1!4b1!4m5!3m4!1s0x3bcb96d53d111d4b:0x471f8bcb641699a7!8m2!3d17.4231815!4d78.4276884?hl=en\">PVR Cinemas</a></td><td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">11:30</label>\n");
      out.write("    </div></td><td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">3:15</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">6:00</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td id = \"time\"><div class=\"radio\">\n");
      out.write("      <label><input type=\"radio\" name=\"optradio\">9:15</label>\n");
      out.write("    </div></td>\n");
      out.write("    <td><button class=\"btn\" data-toggle=\"modal\" data-target=\"#myModal\">BOOK</button></td></tr>\n");
      out.write("    \n");
      out.write("</table>\n");
      out.write("<!-- Modal -->\n");
      out.write("  <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("    \n");
      out.write("      <!--  modal content-->\n");
      out.write("     <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\n");
      out.write("          <h4><span class=\"glyphicon glyphicon-lock\"></span> Tickets</h4>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-body\">\n");
      out.write("          <form role=\"form\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label for=\"psw\"><span class=\"glyphicon glyphicon-shopping-cart\"></span>enter number of persons</label>\n");
      out.write("              <input type=\"number\" min=\"1\" max=\"6\" class=\"form-control\" id=\"psw\" placeholder=\"How many?\">\n");
      out.write("             </div>\n");
      out.write("              <a href=\"SeatsView.jsp\" class=\"btn btn-info\" role=\"button\">Proceed</a>\n");
      out.write("   \n");
      out.write("                        </form>\n");
      out.write("        </div>\n");
      out.write(" \n");
      out.write("\n");
      out.write("<div class=well-lg size=70px style=\"background-color: #313637\">\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
