/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-06-05 03:18:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class trailersView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<style>\n");
      out.write("  video {\n");
      out.write("    width: 100%;\n");
      out.write("    height: auto;\n");
      out.write("}\n");
      out.write("  \n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "themeView.jsp", out, false);
      out.write("\n");
      out.write("<!-- <div class=\"bs-example\">\n");
      out.write("    <div class=\"alert alert-info\">\n");
      out.write("        <a href=\"#\" class=\"close\" data-dismiss=\"alert\">&times;</a>\n");
      out.write("        <strong>Note!</strong> Open the output in a new blank tab (click the arrow button next to \"Show Output\") and resize the browser window to see how responsive videos work.\n");
      out.write("    </div>\n");
      out.write(" -->    <h2>A aa movie Trailer</h2>\n");
      out.write("    <div class=\"embed-responsive embed-responsive-16by9\">\n");
      out.write("        <iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/V4KdbX1xvaI\"></iframe>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <h2>Brahmotsavam movie Trailer</h2>\n");
      out.write("    <div class=\"embed-responsive embed-responsive-16by9\">\n");
      out.write("        <iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/awI21cZggpk\"></iframe>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <h2>Sarinodu movie Trailer</h2>\n");
      out.write("    <div class=\"embed-responsive embed-responsive-16by9\">\n");
      out.write("        <iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/_UGMZ9iVGvo\"></iframe>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <h2>24 movie Trailer</h2>\n");
      out.write("    <div class=\"embed-responsive embed-responsive-16by9\">\n");
      out.write("        <iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/kL9N93iued8\"></iframe>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <h2>Angry Birds movie Trailer</h2>\n");
      out.write("    <div class=\"embed-responsive embed-responsive-16by9\">\n");
      out.write("        <iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/1U2DKKqxHgE\"></iframe>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <h2>BatMan vs SuperMan movie Trailer</h2>\n");
      out.write("    <div class=\"embed-responsive embed-responsive-16by9\">\n");
      out.write("        <iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/eX_iASz1Si8\"></iframe>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <h2>Jungle Book movie Trailer</h2>\n");
      out.write("    <div class=\"embed-responsive embed-responsive-16by9\">\n");
      out.write("        <iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/JCgPGFunkig\"></iframe>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <h2>x-Men Apocolyps movie Trailer</h2>\n");
      out.write("    <div class=\"embed-responsive embed-responsive-16by9\">\n");
      out.write("        <iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/COvnHv42T-A\"></iframe>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <h2>Kapoor and Sons movie Trailer</h2>\n");
      out.write("    <div class=\"embed-responsive embed-responsive-16by9\">\n");
      out.write("        <iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/s7YYt9_KfsM\"></iframe>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write(" <footer class=\"text-center\">\n");
      out.write("  <a class=\"up-arrow\" href=\"#myPage\" data-toggle=\"tooltip\" title=\"TO TOP\">\n");
      out.write("    <span class=\"glyphicon glyphicon-chevron-up\"></span>\n");
      out.write("  </a><br><br>\n");
      out.write("  <p><a href=\"http://www.w3schools.com\" data-toggle=\"tooltip\" title=\"Visit w3schools\">www.GrabYourTicket.com</a></p> \n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("   ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
